### ISSUE TITLE
problem UART comunication

### ISSUE THREAD

**Issue by marcazzan** [bruxy70/Home-Assistant-ESPHome-Weather-Station#13]
Hi I'm testing your weather station with an esp d1 mini and a 3.5 inch nexion display, I loaded the yaml on esp home and everything works, the data updates, but uart doesn't communicate between nexion and d1 mini? what can it be?

**Comment by bruxy70** [comment]
I'd check that the wires are connected correctly (TX to RX and RX to TX). That the speed is set the same in Nextion Editor and ESPHome. If this does not work, I'd try to add a PR that was fixing an error in communication (I think this one should be already included in the ESPHome release, but you can try)

```yaml
external_components:
  - source: github://pr#3657
    components: [ nextion ]
```
